export const HANGMAN_WORDS = Array.from(new Set(`
ARCADE AVENTURE ABRICOT ACADEMIE ACCORDEON AEROPORT AFFICHE AGRICULTURE ALBATROS ALBUM ALCHIMIE
ALIMENT ALPINISME AMBULANCE AMETHYSTE AMIRAL AMPOULE ANANAS ANCRE ANIMAL ANTENNE APPAREIL AQUARIUM
ARCHIPEL ARCHITECTE ARGENT ARMOIRE ASTRONAUTE ATELIER ATHLETE ATMOSPHERE AUBERGE AUTOMOBILE AVION
BAGUETTE BALEINE BALLON BAMBOU BANANE BASKET BATTERIE BIBLIOTHEQUE BICYCLETTE BILLARD BISCUIT BISON
BOISSON BOOMERANG BOUSSOLE BOUTEILLE BRACELET BRANCHE BRIQUE BROCOLI BRONZE CABANE CACAO CACTUS
CAHIER CAMERA CAMPAGNE CANAPE CANYON CAPITAINE CARAVANE CAROTTE CARTABLE CASCADE CASQUE CASSEROLE
CASTOR CAVERNE CEINTURE CERISE CHAMEAU CHAMPION CHANDELLE CHAPEAU CHATEAU CHAUSSETTE CHEMINEE CHEVAL
CHOCOLAT CHOUETTE CIRCUIT CITRON CLAVIER CLOWN COCCINELLE COFFRE COLLINE COMETE CONSOLE CORAIL CORBEAU
COURONNE COUSSIN CRAYON CROCODILE CUISINE CYCLISTE DAUPHIN DESERT DIAMANT DINOSAURE DISQUE DRAGON
DRAPEAU ECHELLE ECOLE ECLAIR ECUREUIL ELEPHANT ENIGME ESCALADE ESPACE ETOILE FALAISE FANTOME FARINE
FENETRE FESTIVAL FEUILLE FLAMANT FLEUVE FLOCON FORET FORTERESSE FOSSE FOUCHE FOURCHETTE FROMAGE FUSEE
GALAXIE GARAGE GATEAU GIRAFE GLACIER GORILLE GRENOUILLE GUITARE HAMAC HARMONICA HERISSON HIBOU HOCKEY
HORLOGE HORIZON HOTEL ILE IMPRIMANTE INSECTE JARDIN JONQUILLE JOURNAL JUMELLES KANGOUROU KAYAK KOALA
LABYRINTHE LAMPE LANTERNE LEOPARD LICORNE LIVRE LOCOMOTIVE LUNE LUNETTES MACHINE MAGICIEN MAGNETIQUE
MAISON MANDARINE MANETTE MANGUE MARATHON MARTEAU MASQUE MEDAILLE MELON METEORITE MICROPHONE MONTAGNE
MONTGOLFIERE MOTEUR MOUETTE MOUSTACHE MOUTON MUSIQUE MYSTERE NATURE NAVETTE NEIGE NUAGE OCEAN OCTOPUS
ORDINATEUR ORCHESTRE ORIGAMI PANDA PANIER PAPILLON PARACHUTE PARAPLUIE PASTAQUE PATINAGE PELICAN PENDULE
PERROQUET PHARE PIANO PIEUVRE PILOTE PINCEAU PINGOUIN PIRATE PIXEL PLANETE PLATEAU PLONGEE POIRE POISSON
POMME PONT PORTAIL POTAGER PRAIRIE PRISME PUZZLE PYRAMIDE RAQUETTE RENARD ROBOT ROCHER ROCKET ROLLER
ROSE ROUE RUBIS SABLE SACADOS SATELLITE SAXOPHONE SCORPION SERPENT SKATEBOARD SOLEIL SOUSMARIN SPHINX
SPORT STADE STATUE SURF TABLETTE TAMBOUR TELESCOPE TEMPLE TEMPETE TIGRE TOBOGGAN TOMATE TORTUE TOURNEVIS
TRAIN TRAMPOLINE TRESOR TRIANGLE TROMPETTE TROPHEE TUNNEL TURQUOISE UNIFORME VAISSEAU VALISE VELO
VENTILATEUR VIOLON VOLCAN VOYAGE ZEBRE
ACCELERATION ACOUSTIQUE ADRENALINE ALGORITHME ALLIANCE AMBASSADE AMPHIBIE ANIMATION ANTIQUITE APICULTEUR
ARBITRE ARCHIVES ARMATURE ARTIFICE ASTRONOMIE AVENTURIER BALANCOIRE BARRIERE BATEAU BAVARDAGE BEIGNET
BOULANGER BOUSSOLE BRICOLAGE BROUILLARD CABRIOLET CALENDRIER CAMOUFLAGE CAPTEUR CARNAVAL CARROUSEL
CATHEDRALE CERF_VOLANT CHAMPIGNON CHANSON CHEVALIER CHRONOMETRE CINEMA CITROUILLE COLLECTION COMPAS
CONSTELLATION CONTINENT COQUILLAGE CRATERE CREPUSCULE CRISTAL DELTAPLANE DOCUMENT DOMINO DRONE ECHARPE
ECLIPSE ECOSYSTEME ECOUTEURS EMERAUDE ENCYCLOPEDIE ENERGIE ENVELOPPE ESCARGOT EXPLORATEUR FALAFEL
FAMILLE FENNEC FERMETURE FEUILLAGE FEUXARTIFICE FIGURINE FLUTE FOOTBALL FORMULE FOURMI FRAMBOISE
FUNAMBULE GEOMETRIE GIROUETTE GLOBE GOURDE GRAFFITI HAMBURGER HELICOPTERE HISTOIRE HOLOGRAMME ICEBERG
JAGUAR JEUVIDEO JUMELAGE KIOSQUE LABORATOIRE LACET LAVANDE LEMURIEN LIMONADE LUCIOLE MARMOTTE MEDUSE
MINIGOLF MOSAIQUE NAVIGATION NEBULEUSE ORAGE ORCHIDEE PANORAMA PANTHERE PARC PALMIER PENDULE PENTATHLON
PHOTOGRAPHIE PLANISPHERE PLATEFORME PLUME PODIUM POLAROID PORTABLE PROJECTEUR QUARTZ RANDONNEE RECIF
ROBOTIQUE SANDWICH SCAPHANDRE SCULPTURE SEMAPHORE SILHOUETTE SIMULATEUR SKATE SNOWBOARD SONNETTE
SPIRALE STALACTITE SURPRISE SYMPHONIE TELECOMMANDE TERRARIUM THERMOMETRE TORNADE TRAJECTOIRE TRIBUNE
TROTTINETTE UNIVERS VITRAIL VOLLEYBALL WAGON WEBCAM XYLOPHONE ZODIAQUE
`.replace(/_/g, '').trim().split(/\s+/).filter(Boolean)));

export function randomHangmanWord() {
  return HANGMAN_WORDS[Math.floor(Math.random() * HANGMAN_WORDS.length)] ?? "ARCADE";
}
