from pathlib import Path

p = Path('app/PongGame.tsx')
s = p.read_text(encoding='utf-8')

def replace_once(old: str, new: str):
    global s
    count = s.count(old)
    if count != 1:
        raise SystemExit(f'expected exactly one occurrence, got {count}: {old[:120]!r}')
    s = s.replace(old, new, 1)

replace_once('''const ICE_SERVERS: RTCIceServer[] = [\n  { urls: "stun:stun.l.google.com:19302" },\n  { urls: "stun:stun1.l.google.com:19302" },\n];''', '''const ICE_SERVERS: RTCIceServer[] = [\n  { urls: "stun:stun.l.google.com:19302" },\n  { urls: "stun:stun1.l.google.com:19302" },\n  { urls: "stun:stun.relay.metered.ca:80" },\n  { urls: "turn:global.relay.metered.ca:80", username: "openrelayproject", credential: "openrelayproject" },\n  { urls: "turn:global.relay.metered.ca:80?transport=tcp", username: "openrelayproject", credential: "openrelayproject" },\n  { urls: "turns:global.relay.metered.ca:443?transport=tcp", username: "openrelayproject", credential: "openrelayproject" },\n];''')

replace_once('const timeout = window.setTimeout(() => controller.abort(), 3500);', 'const timeout = window.setTimeout(() => controller.abort(), 8000);')

replace_once('''  const lastDirectInputRef = useRef(0);\n  const lastFallbackInputRef = useRef(0);\n  const keysRef = useRef({ up: false, down: false });''', '''  const lastDirectInputRef = useRef(0);\n  const lastFallbackInputRef = useRef(0);\n  const peerStartedAtRef = useRef<Map<string, number>>(new Map());\n  const stateSequenceRef = useRef(0);\n  const inputSequenceRef = useRef(0);\n  const lastRemoteStateSequenceRef = useRef(-1);\n  const lastRemoteInputSequenceRef = useRef<Map<string, number>>(new Map());\n  const keysRef = useRef({ up: false, down: false });''')

replace_once('''    directAckRef.current.delete(peerId);\n    reconnectingRef.current.delete(peerId);''', '''    directAckRef.current.delete(peerId);\n    peerStartedAtRef.current.delete(peerId);\n    reconnectingRef.current.delete(peerId);''')

replace_once('''    pendingIceRef.current.clear();\n    directAckRef.current.clear();\n    lastDirectStateAtRef.current = 0;\n    reconnectingRef.current.clear();''', '''    pendingIceRef.current.clear();\n    directAckRef.current.clear();\n    peerStartedAtRef.current.clear();\n    lastDirectStateAtRef.current = 0;\n    reconnectingRef.current.clear();''')

replace_once('''  const receiveInput = useCallback((senderId: string, payload: unknown) => {\n    const current = gameRef.current;\n    const simulation = simulationRef.current;\n    if (!current || !simulation || room.hostId !== user.id || !payload || typeof payload !== "object") return;\n    const player = current.players.find((entry) => entry.userId === senderId);\n    if (!player) return;\n    const y = Number((payload as { y?: unknown }).y);\n    if (Number.isFinite(y)) simulation.targets[senderId] = clampPaddleY(y);\n  }, [room.hostId, user.id]);''', '''  const receiveInput = useCallback((senderId: string, payload: unknown, sequenceValue?: unknown) => {\n    const sequence = Number(sequenceValue);\n    if (Number.isFinite(sequence)) {\n      const previous = lastRemoteInputSequenceRef.current.get(senderId) ?? -1;\n      if (sequence <= previous) return;\n      lastRemoteInputSequenceRef.current.set(senderId, sequence);\n    }\n    const current = gameRef.current;\n    const simulation = simulationRef.current;\n    if (!current || !simulation || room.hostId !== user.id || !payload || typeof payload !== "object") return;\n    const player = current.players.find((entry) => entry.userId === senderId);\n    if (!player) return;\n    const y = Number((payload as { y?: unknown }).y);\n    if (Number.isFinite(y)) simulation.targets[senderId] = clampPaddleY(y);\n  }, [room.hostId, user.id]);''')

replace_once('''  const receiveState = useCallback((payload: unknown) => {\n    if (!payload || typeof payload !== "object") return;\n    const incoming = payload as Frame;\n    if (!incoming.ball || !incoming.paddles) return;\n    const copy = cloneFrame(incoming);\n    remoteSnapshotRef.current = { frame: copy, receivedAt: performance.now() };\n    if (!isHost) setFrame(copy);\n  }, [isHost]);''', '''  const receiveState = useCallback((payload: unknown, sequenceValue?: unknown) => {\n    const sequence = Number(sequenceValue);\n    if (Number.isFinite(sequence)) {\n      if (sequence <= lastRemoteStateSequenceRef.current) return;\n      lastRemoteStateSequenceRef.current = sequence;\n    }\n    if (!payload || typeof payload !== "object") return;\n    const incoming = payload as Frame;\n    if (!incoming.ball || !incoming.paddles) return;\n    const copy = cloneFrame(incoming);\n    if (copy.pauseUntil > Date.now()) { localYRef.current = 0.5; draggingRef.current = false; }\n    remoteSnapshotRef.current = { frame: copy, receivedAt: performance.now() };\n    if (!isHost) setFrame(copy);\n  }, [isHost]);''')

replace_once('''      if (hostSide && simulationRef.current && channel.readyState === "open") {\n        try { channel.send(JSON.stringify({ type: "state", state: simulationRef.current.frame })); } catch {}\n      }''', '''      if (hostSide && simulationRef.current && channel.readyState === "open") {\n        try { channel.send(JSON.stringify({ type: "state", seq: ++stateSequenceRef.current, state: simulationRef.current.frame })); } catch {}\n      }''')

replace_once('''        if (hostSide && message.type === "input") receiveInput(peerId, message.input);\n        else if (hostSide && message.type === "ack") directAckRef.current.set(peerId, performance.now());\n        else if (!hostSide && message.type === "state") {\n          lastDirectStateAtRef.current = performance.now();\n          receiveState(message.state);''', '''        if (hostSide && message.type === "input") receiveInput(peerId, message.input, message.seq);\n        else if (hostSide && message.type === "ack") directAckRef.current.set(peerId, performance.now());\n        else if (!hostSide && message.type === "state") {\n          lastDirectStateAtRef.current = performance.now();\n          receiveState(message.state, message.seq);''')

replace_once('''    const pc = new RTCPeerConnection({ iceServers: ICE_SERVERS });\n    const entry: PeerEntry = { pc, dc: null };\n    peersRef.current.set(peerId, entry);''', '''    const pc = new RTCPeerConnection({ iceServers: ICE_SERVERS, iceCandidatePoolSize: 4 });\n    const entry: PeerEntry = { pc, dc: null };\n    peersRef.current.set(peerId, entry);\n    peerStartedAtRef.current.set(peerId, performance.now());''')

replace_once('''    const old = peersRef.current.get(peerId);\n    const ackAge = performance.now() - (directAckRef.current.get(peerId) ?? 0);\n    if (old?.dc?.readyState === "open" && ackAge < 1600) return;\n    if (old?.pc.connectionState === "connecting") return;''', '''    const old = peersRef.current.get(peerId);\n    const now = performance.now();\n    const ackAge = now - (directAckRef.current.get(peerId) ?? 0);\n    const connectingAge = now - (peerStartedAtRef.current.get(peerId) ?? 0);\n    if (old?.dc?.readyState === "open" && ackAge < 4500) return;\n    if ((old?.pc.connectionState === "connecting" || old?.pc.connectionState === "new") && connectingAge < 6500) return;''')

replace_once('''      const channel = entry.pc.createDataChannel("retro-pong", { ordered: false, maxRetransmits: 0 });''', '''      const channel = entry.pc.createDataChannel("retro-pong", { ordered: false, maxPacketLifeTime: 240 });''')

replace_once('''    if (signal.kind === "input") {\n      if (user.id === hostId) receiveInput(signal.senderId, signal.payload);\n      return;\n    }\n    if (signal.kind === "state") {\n      if (user.id !== hostId && signal.senderId === hostId) receiveState(signal.payload);\n      return;\n    }''', '''    if (signal.kind === "input") {\n      if (user.id === hostId) {\n        const wrapped = signal.payload as { seq?: unknown; input?: unknown } | null;\n        receiveInput(signal.senderId, wrapped && typeof wrapped === "object" && "input" in wrapped ? wrapped.input : signal.payload, wrapped?.seq);\n      }\n      return;\n    }\n    if (signal.kind === "state") {\n      if (user.id !== hostId && signal.senderId === hostId) {\n        const wrapped = signal.payload as { seq?: unknown; state?: unknown } | null;\n        receiveState(wrapped && typeof wrapped === "object" && "state" in wrapped ? wrapped.state : signal.payload, wrapped?.seq);\n      }\n      return;\n    }''')

replace_once('''        timer = window.setTimeout(() => void pollState(), next.status === "lobby" ? 1100 : 2600);''', '''        timer = window.setTimeout(() => void pollState(), next.status === "lobby" ? 800 : 6000);''')
replace_once('''        timer = window.setTimeout(() => void pollState(), 1600);''', '''        timer = window.setTimeout(() => void pollState(), gameRef.current?.status === "playing" ? 7000 : 1800);''')

replace_once('''    signalCursorRef.current = 0;\n    localYRef.current = 0.5;\n    if (isHost) {''', '''    signalCursorRef.current = 0;\n    localYRef.current = 0.5;\n    stateSequenceRef.current = 0;\n    inputSequenceRef.current = 0;\n    lastRemoteStateSequenceRef.current = -1;\n    lastRemoteInputSequenceRef.current.clear();\n    if (isHost) {''')

replace_once('''      const healthy = isHost\n        ? peer?.dc?.readyState === "open" && performance.now() - (directAckRef.current.get(peerId) ?? 0) < 1200\n        : peer?.dc?.readyState === "open" && performance.now() - lastDirectStateAtRef.current < 1200;\n      timer = window.setTimeout(() => void signalPoll(), healthy ? 700 : 120);''', '''      const healthy = isHost\n        ? peer?.dc?.readyState === "open" && performance.now() - (directAckRef.current.get(peerId) ?? 0) < 2500\n        : peer?.dc?.readyState === "open" && performance.now() - lastDirectStateAtRef.current < 2500;\n      timer = window.setTimeout(() => void signalPoll(), healthy ? 850 : 70);''')

replace_once('''    const id = window.setInterval(ensure, 900);''', '''    const id = window.setInterval(ensure, 1500);''')

replace_once('''      if (now - simulation.lastBroadcast >= 33) {\n        simulation.lastBroadcast = now;\n        const message = JSON.stringify({ type: "state", state: simulation.frame });\n        for (const player of current.players) {\n          if (player.userId === user.id || player.isBot) continue;\n          const channel = peersRef.current.get(player.userId)?.dc;\n          if (channel?.readyState === "open") { try { channel.send(message); } catch {} }\n        }\n      }\n      if (now - simulation.lastFallbackBroadcast >= 150) {\n        simulation.lastFallbackBroadcast = now;\n        for (const player of current.players) {\n          if (player.userId === user.id || player.isBot) continue;\n          const channel = peersRef.current.get(player.userId)?.dc;\n          const healthy = channel?.readyState === "open" && now - (directAckRef.current.get(player.userId) ?? 0) < 900;\n          if (!healthy) void sendSignal(player.userId, "state", simulation.frame).catch(() => undefined);\n        }\n      }''', '''      if (now - simulation.lastBroadcast >= 33) {\n        simulation.lastBroadcast = now;\n        const seq = ++stateSequenceRef.current;\n        const message = JSON.stringify({ type: "state", seq, state: simulation.frame });\n        for (const player of current.players) {\n          if (player.userId === user.id || player.isBot) continue;\n          const channel = peersRef.current.get(player.userId)?.dc;\n          if (channel?.readyState === "open" && channel.bufferedAmount < 32768) { try { channel.send(message); } catch {} }\n        }\n      }\n      if (now - simulation.lastFallbackBroadcast >= 85) {\n        simulation.lastFallbackBroadcast = now;\n        const seq = ++stateSequenceRef.current;\n        for (const player of current.players) {\n          if (player.userId === user.id || player.isBot) continue;\n          const channel = peersRef.current.get(player.userId)?.dc;\n          const healthy = channel?.readyState === "open" && channel.bufferedAmount < 65536 && now - (directAckRef.current.get(player.userId) ?? 0) < 1800;\n          if (!healthy) void sendSignal(player.userId, "state", { seq, state: simulation.frame }).catch(() => undefined);\n        }\n      }''')

replace_once('''  const sendInput = useCallback((force = false) => {\n    if (isHost) return;\n    const now = performance.now();\n    const channel = peersRef.current.get(room.hostId)?.dc;\n    const directHealthy = channel?.readyState === "open" && now - lastDirectStateAtRef.current < 1200;\n    if (channel?.readyState === "open") {\n      if (force || now - lastDirectInputRef.current >= 12) {\n        lastDirectInputRef.current = now;\n        try { channel.send(JSON.stringify({ type: "input", input: { y: localYRef.current } })); } catch {}\n      }\n      if (directHealthy) return;\n    }\n    if (force || now - lastFallbackInputRef.current >= 100) {\n      lastFallbackInputRef.current = now;\n      void sendSignal(room.hostId, "input", { y: localYRef.current }).catch(() => undefined);\n    }\n  }, [isHost, room.hostId, sendSignal]);''', '''  const sendInput = useCallback((force = false) => {\n    if (isHost) return;\n    const now = performance.now();\n    const channel = peersRef.current.get(room.hostId)?.dc;\n    const directHealthy = channel?.readyState === "open" && now - lastDirectStateAtRef.current < 2500;\n    if (channel?.readyState === "open") {\n      if (force || now - lastDirectInputRef.current >= 12) {\n        lastDirectInputRef.current = now;\n        const seq = ++inputSequenceRef.current;\n        try { channel.send(JSON.stringify({ type: "input", seq, input: { y: localYRef.current } })); } catch {}\n      }\n      if (directHealthy) return;\n    }\n    if (force || now - lastFallbackInputRef.current >= 70) {\n      lastFallbackInputRef.current = now;\n      const seq = ++inputSequenceRef.current;\n      void sendSignal(room.hostId, "input", { seq, input: { y: localYRef.current } }).catch(() => undefined);\n    }\n  }, [isHost, room.hostId, sendSignal]);''')

replace_once('''        {isHost ? <button className="primaryButton" disabled={busy || online !== 2} onClick={() => void start(false)}>{busy ? "Lancement…" : "Lancer Pong"}</button> : <small>En attente de l'hôte…</small>}''', '''        {isHost ? <><button className="primaryButton pongHostStartButton" disabled={busy || online !== 2} onClick={() => void start(false)}>{busy ? "Démarrage…" : "Démarrer la partie"}</button><small>{online === 2 ? "C'est toi qui décides quand le match commence." : "Il faut exactement 2 joueurs connectés."}</small></> : <small>En attente que l'hôte démarre la partie…</small>}''')

p.write_text(s, encoding='utf-8')
print('Pong stability patch applied.')
